# Generated by Django 6.1 on 2026-08-14 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('desc', models.TextField()),
                ('earned', models.BooleanField(default=False)),
                ('rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AchievementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=32)),
                ('earned', models.JSONField(default=list)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedReport',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=8)),
                ('year', models.CharField(max_length=8)),
                ('month', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(max_length=128)),
                ('range', models.CharField(max_length=64)),
                ('net', models.CharField(max_length=16)),
                ('win_rate', models.CharField(max_length=8)),
                ('lines', models.JSONField(default=list)),
                ('sort_key', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sort_key'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('details', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trades', models.PositiveIntegerField(default=0)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CoachInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Coach insights',
            },
        ),
        migrations.CreateModel(
            name='CoachPeriod',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=8)),
                ('label', models.CharField(max_length=64)),
                ('range', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('net', models.CharField(max_length=16)),
                ('win_rate', models.CharField(max_length=8)),
                ('scores', models.JSONField(default=list)),
                ('stats', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('action_plan', models.JSONField(default=list)),
                ('sort_key', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-sort_key'],
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=16)),
                ('currency', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=128)),
                ('impact', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=8)),
                ('forecast', models.CharField(max_length=24)),
                ('previous', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='EquityCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ForexSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('progress', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(default='primary', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=16)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=320)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('تخفیف', 'تخفیف'), ('آپدیت', 'آپدیت'), ('اطلاعیه', 'اطلاعیه'), ('آموزش', 'آموزش')], max_length=16)),
                ('date', models.DateField()),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-pinned'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('news', 'news'), ('ticket', 'ticket'), ('system', 'system')], max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('desc', models.CharField(max_length=320)),
                ('time', models.DateField()),
                ('link', models.CharField(blank=True, max_length=160)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('plan', models.CharField(max_length=32)),
                ('amount', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('status', models.CharField(default='موفق', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=32)),
                ('tagline', models.CharField(max_length=160)),
                ('portfolio_limit', models.CharField(max_length=64)),
                ('features', models.JSONField(default=list)),
                ('cta', models.CharField(max_length=64)),
                ('highlight', models.BooleanField(default=False)),
                ('sellable', models.BooleanField(default=True)),
                ('users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(max_length=32)),
                ('status', models.CharField(default='فعال', max_length=16)),
                ('joined', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('broker', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('initial', models.DecimalField(decimal_places=2, max_digits=14)),
                ('leverage', models.CharField(max_length=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('trades', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='فعال', max_length=16)),
                ('strategy', models.CharField(default='', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('signups', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('min_pct', models.PositiveIntegerField()),
                ('max_pct', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('days_left', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=160)),
                ('topic', models.CharField(choices=[('فنی', 'فنی'), ('پرداخت', 'پرداخت'), ('حساب کاربری', 'حساب کاربری'), ('اشتراک', 'اشتراک'), ('سایر', 'سایر')], max_length=16)),
                ('status', models.CharField(choices=[('باز', 'باز'), ('در حال بررسی', 'در حال بررسی'), ('پاسخ داده شد', 'پاسخ داده شد'), ('بسته', 'بسته')], default='باز', max_length=16)),
                ('user', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('default_visible', models.BooleanField(default=True)),
                ('admin_enabled', models.BooleanField(default=True)),
                ('numeric', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('week', models.CharField(max_length=32)),
                ('month', models.CharField(max_length=32)),
                ('trade_id', models.CharField(blank=True, max_length=24)),
                ('symbol', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('mistakes', models.TextField(blank=True)),
                ('lesson', models.TextField(blank=True)),
                ('emotion', models.CharField(default='', max_length=32)),
                ('plan', models.BooleanField(default=True)),
                ('favorite', models.BooleanField(default=False)),
                ('html', models.TextField(blank=True)),
                ('blocks', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.journalgroup')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=8)),
                ('author_name', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.CharField(max_length=24)),
                ('symbol', models.CharField(max_length=12)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('entry', models.DecimalField(decimal_places=5, max_digits=14)),
                ('exit', models.DecimalField(decimal_places=5, max_digits=14)),
                ('sl', models.DecimalField(decimal_places=5, max_digits=14)),
                ('tp', models.DecimalField(decimal_places=5, max_digits=14)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pips', models.DecimalField(decimal_places=1, max_digits=8)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swap', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('magic', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=128)),
                ('reason', models.CharField(default='Client', max_length=32)),
                ('strategy', models.CharField(default='', max_length=64)),
                ('followed_plan', models.BooleanField(default=True)),
                ('emotion', models.CharField(default='آرام', max_length=32)),
                ('screenshots', models.JSONField(default=list)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_set', to='api.portfolio')),
            ],
            options={
                'ordering': ['-close_time'],
            },
        ),
    ]
