# Generated by Django 6.1 on 2026-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachperiod',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
