# Generated by Django 6.1 on 2026-08-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trader', 'تریدر'), ('professional', 'حرفه\u200cای'), ('master', 'استاد'), ('admin', 'مدیر'), ('vip', 'ویژه'), ('trader-vip', 'تریدر ویژه'), ('professional-vip', 'حرفه\u200cای ویژه'), ('master-vip', 'استاد ویژه')], default='trader', max_length=24),
        ),
    ]
