# Generated by Django 6.1 on 2026-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_platformuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(default='رایگان', max_length=32),
        ),
    ]
