# Generated by Django 6.1 on 2026-09-04 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachinsights',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.portfolio'),
        ),
        migrations.AddField(
            model_name='coachperiod',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='strategy',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
