# Generated by Django 6.1 on 2026-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_normalize_single_active_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_portfolios',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_trades_per_month',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
