# Generated by Django 6.1 on 2026-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_plan_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR')], default='INFO', max_length=16)),
                ('message', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
