# Generated by Django 6.1 on 2026-09-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.portfolio'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.portfolio'),
        ),
        migrations.AddField(
            model_name='journalgroup',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.portfolio'),
        ),
    ]
