/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAiCoachRouteImport } from './routes/app.ai-coach'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppJournalRouteImport } from './routes/app.journal'
import { Route as AppPortfoliosRouteImport } from './routes/app.portfolios'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppAdminApisRouteImport } from './routes/app.admin.apis'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminDashboardRouteImport } from './routes/app.admin.dashboard'
import { Route as AppAdminLogsRouteImport } from './routes/app.admin.logs'
import { Route as AppAdminNewsRouteImport } from './routes/app.admin.news'
import { Route as AppAdminPaymentsRouteImport } from './routes/app.admin.payments'
import { Route as AppAdminPlansRouteImport } from './routes/app.admin.plans'
import { Route as AppAdminTicketsRouteImport } from './routes/app.admin.tickets'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppNewsIndexRouteImport } from './routes/app.news.index'
import { Route as AppNewsIdRouteImport } from './routes/app.news.$id'
import { Route as AppTradesIndexRouteImport } from './routes/app.trades.index'
import { Route as AppTradesIdRouteImport } from './routes/app.trades.$id'
import { Route as AppTradesNewRouteImport } from './routes/app.trades.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCoachRoute = AppAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfoliosRoute = AppPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApisRoute = AppAdminApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNewsRoute = AppAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPlansRoute = AppAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminTicketsRoute = AppAdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIdRoute = AppNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesIndexRoute = AppTradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesIdRoute = AppTradesIdRouteImport.update({
  id: '/trades/$id',
  path: '/trades/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTradesNewRoute = AppTradesNewRouteImport.update({
  id: '/trades/new',
  path: '/trades/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/admin/apis': typeof AppAdminApisRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/news': typeof AppAdminNewsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/tickets': typeof AppAdminTicketsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/trades/$id': typeof AppTradesIdRoute
  '/app/trades/new': typeof AppTradesNewRoute
  '/app/news/': typeof AppNewsIndexRoute
  '/app/trades/': typeof AppTradesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/admin/apis': typeof AppAdminApisRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/news': typeof AppAdminNewsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/tickets': typeof AppAdminTicketsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/trades/$id': typeof AppTradesIdRoute
  '/app/trades/new': typeof AppTradesNewRoute
  '/app/news': typeof AppNewsIndexRoute
  '/app/trades': typeof AppTradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ai-coach': typeof AppAiCoachRoute
  '/app/billing': typeof AppBillingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/journal': typeof AppJournalRoute
  '/app/portfolios': typeof AppPortfoliosRoute
  '/app/risk': typeof AppRiskRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/admin/apis': typeof AppAdminApisRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/logs': typeof AppAdminLogsRoute
  '/app/admin/news': typeof AppAdminNewsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/plans': typeof AppAdminPlansRoute
  '/app/admin/tickets': typeof AppAdminTicketsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/trades/$id': typeof AppTradesIdRoute
  '/app/trades/new': typeof AppTradesNewRoute
  '/app/news/': typeof AppNewsIndexRoute
  '/app/trades/': typeof AppTradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/support'
    | '/app/admin/apis'
    | '/app/admin/audit'
    | '/app/admin/dashboard'
    | '/app/admin/logs'
    | '/app/admin/news'
    | '/app/admin/payments'
    | '/app/admin/plans'
    | '/app/admin/tickets'
    | '/app/admin/users'
    | '/app/news/$id'
    | '/app/trades/$id'
    | '/app/trades/new'
    | '/app/news/'
    | '/app/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/support'
    | '/app/admin/apis'
    | '/app/admin/audit'
    | '/app/admin/dashboard'
    | '/app/admin/logs'
    | '/app/admin/news'
    | '/app/admin/payments'
    | '/app/admin/plans'
    | '/app/admin/tickets'
    | '/app/admin/users'
    | '/app/news/$id'
    | '/app/trades/$id'
    | '/app/trades/new'
    | '/app/news'
    | '/app/trades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/ai-coach'
    | '/app/billing'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/goals'
    | '/app/journal'
    | '/app/portfolios'
    | '/app/risk'
    | '/app/settings'
    | '/app/support'
    | '/app/admin/apis'
    | '/app/admin/audit'
    | '/app/admin/dashboard'
    | '/app/admin/logs'
    | '/app/admin/news'
    | '/app/admin/payments'
    | '/app/admin/plans'
    | '/app/admin/tickets'
    | '/app/admin/users'
    | '/app/news/$id'
    | '/app/trades/$id'
    | '/app/trades/new'
    | '/app/news/'
    | '/app/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-coach': {
      id: '/app/ai-coach'
      path: '/ai-coach'
      fullPath: '/app/ai-coach'
      preLoaderRoute: typeof AppAiCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/journal': {
      id: '/app/journal'
      path: '/journal'
      fullPath: '/app/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolios': {
      id: '/app/portfolios'
      path: '/portfolios'
      fullPath: '/app/portfolios'
      preLoaderRoute: typeof AppPortfoliosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/apis': {
      id: '/app/admin/apis'
      path: '/apis'
      fullPath: '/app/admin/apis'
      preLoaderRoute: typeof AppAdminApisRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/logs': {
      id: '/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/news': {
      id: '/app/admin/news'
      path: '/news'
      fullPath: '/app/admin/news'
      preLoaderRoute: typeof AppAdminNewsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/payments': {
      id: '/app/admin/payments'
      path: '/payments'
      fullPath: '/app/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/plans': {
      id: '/app/admin/plans'
      path: '/plans'
      fullPath: '/app/admin/plans'
      preLoaderRoute: typeof AppAdminPlansRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/tickets': {
      id: '/app/admin/tickets'
      path: '/tickets'
      fullPath: '/app/admin/tickets'
      preLoaderRoute: typeof AppAdminTicketsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/news/': {
      id: '/app/news/'
      path: '/news'
      fullPath: '/app/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news/$id': {
      id: '/app/news/$id'
      path: '/news/$id'
      fullPath: '/app/news/$id'
      preLoaderRoute: typeof AppNewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades/': {
      id: '/app/trades/'
      path: '/trades'
      fullPath: '/app/trades/'
      preLoaderRoute: typeof AppTradesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades/$id': {
      id: '/app/trades/$id'
      path: '/trades/$id'
      fullPath: '/app/trades/$id'
      preLoaderRoute: typeof AppTradesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trades/new': {
      id: '/app/trades/new'
      path: '/trades/new'
      fullPath: '/app/trades/new'
      preLoaderRoute: typeof AppTradesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminApisRoute: typeof AppAdminApisRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminNewsRoute: typeof AppAdminNewsRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminPlansRoute: typeof AppAdminPlansRoute
  AppAdminTicketsRoute: typeof AppAdminTicketsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminApisRoute: AppAdminApisRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminNewsRoute: AppAdminNewsRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminPlansRoute: AppAdminPlansRoute,
  AppAdminTicketsRoute: AppAdminTicketsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiCoachRoute: typeof AppAiCoachRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppPortfoliosRoute: typeof AppPortfoliosRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppNewsIdRoute: typeof AppNewsIdRoute
  AppTradesIdRoute: typeof AppTradesIdRoute
  AppTradesNewRoute: typeof AppTradesNewRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
  AppTradesIndexRoute: typeof AppTradesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiCoachRoute: AppAiCoachRoute,
  AppBillingRoute: AppBillingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppJournalRoute: AppJournalRoute,
  AppPortfoliosRoute: AppPortfoliosRoute,
  AppRiskRoute: AppRiskRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppNewsIdRoute: AppNewsIdRoute,
  AppTradesIdRoute: AppTradesIdRoute,
  AppTradesNewRoute: AppTradesNewRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
  AppTradesIndexRoute: AppTradesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
